//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for AttributeTypeSimpleType.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="AttributeTypeSimpleType"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="BOOLEAN"/&amp;gt;
 *     &amp;lt;enumeration value="BOOLEAN_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="BYTE"/&amp;gt;
 *     &amp;lt;enumeration value="BYTE_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="DATE"/&amp;gt;
 *     &amp;lt;enumeration value="DATE_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="DOUBLE"/&amp;gt;
 *     &amp;lt;enumeration value="DOUBLE_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="FILE_PATH_STRING"/&amp;gt;
 *     &amp;lt;enumeration value="FLOAT"/&amp;gt;
 *     &amp;lt;enumeration value="FLOAT_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="FOLDER"/&amp;gt;
 *     &amp;lt;enumeration value="INT_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="INTEGER"/&amp;gt;
 *     &amp;lt;enumeration value="LIST"/&amp;gt;
 *     &amp;lt;enumeration value="LONG"/&amp;gt;
 *     &amp;lt;enumeration value="LONG_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="MAP"/&amp;gt;
 *     &amp;lt;enumeration value="NULL"/&amp;gt;
 *     &amp;lt;enumeration value="OBJECT"/&amp;gt;
 *     &amp;lt;enumeration value="PASSWORD_STRING"/&amp;gt;
 *     &amp;lt;enumeration value="PATH_STRING"/&amp;gt;
 *     &amp;lt;enumeration value="SET"/&amp;gt;
 *     &amp;lt;enumeration value="SHORT"/&amp;gt;
 *     &amp;lt;enumeration value="SHORT_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="STRING"/&amp;gt;
 *     &amp;lt;enumeration value="STRING_ARRAY"/&amp;gt;
 *     &amp;lt;enumeration value="UNKNOWN"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "AttributeTypeSimpleType")
@XmlEnum
public enum AttributeTypeSimpleType {

    BOOLEAN,
    BOOLEAN_ARRAY,
    BYTE,
    BYTE_ARRAY,
    DATE,
    DATE_ARRAY,
    DOUBLE,
    DOUBLE_ARRAY,
    FILE_PATH_STRING,
    FLOAT,
    FLOAT_ARRAY,
    FOLDER,
    INT_ARRAY,
    INTEGER,
    LIST,
    LONG,
    LONG_ARRAY,
    MAP,
    NULL,
    OBJECT,
    PASSWORD_STRING,
    PATH_STRING,
    SET,
    SHORT,
    SHORT_ARRAY,
    STRING,
    STRING_ARRAY,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static AttributeTypeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
