//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.30 at 05:10:56 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for AttributeTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="BOOLEAN_ARRAY"/>
 *     &lt;enumeration value="BYTE"/>
 *     &lt;enumeration value="BYTE_ARRAY"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="DATE_ARRAY"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="DOUBLE_ARRAY"/>
 *     &lt;enumeration value="FILE_PATH_STRING"/>
 *     &lt;enumeration value="FLOAT"/>
 *     &lt;enumeration value="FLOAT_ARRAY"/>
 *     &lt;enumeration value="FOLDER"/>
 *     &lt;enumeration value="INT_ARRAY"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="LIST"/>
 *     &lt;enumeration value="LONG"/>
 *     &lt;enumeration value="LONG_ARRAY"/>
 *     &lt;enumeration value="MAP"/>
 *     &lt;enumeration value="NULL"/>
 *     &lt;enumeration value="OBJECT"/>
 *     &lt;enumeration value="PASSWORD_STRING"/>
 *     &lt;enumeration value="PATH_STRING"/>
 *     &lt;enumeration value="SET"/>
 *     &lt;enumeration value="SHORT"/>
 *     &lt;enumeration value="SHORT_ARRAY"/>
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="STRING_ARRAY"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum AttributeTypeSimpleType {

    BOOLEAN,
    BOOLEAN_ARRAY,
    BYTE,
    BYTE_ARRAY,
    DATE,
    DATE_ARRAY,
    DOUBLE,
    DOUBLE_ARRAY,
    FILE_PATH_STRING,
    FLOAT,
    FLOAT_ARRAY,
    FOLDER,
    INT_ARRAY,
    INTEGER,
    LIST,
    LONG,
    LONG_ARRAY,
    MAP,
    NULL,
    OBJECT,
    PASSWORD_STRING,
    PATH_STRING,
    SET,
    SHORT,
    SHORT_ARRAY,
    STRING,
    STRING_ARRAY,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static AttributeTypeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
