//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Introspect Data Source Type: Provides a way to introspect a data source. 
 * 			Introspection is the process of analyzing resources in a data source and creating resources withing the DV that represent them.
 * 		
 * 
 * &lt;p&gt;Java class for IntrospectDataSourceType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="IntrospectDataSourceType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="resourcePath" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="runInBackgroundTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="reportDetail"&amp;gt;
 *           &amp;lt;simpleType&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *               &amp;lt;enumeration value="SUMMARY"/&amp;gt;
 *               &amp;lt;enumeration value="SIMPLE"/&amp;gt;
 *               &amp;lt;enumeration value="SIMPLE_COMPRESSED"/&amp;gt;
 *               &amp;lt;enumeration value="FULL"/&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/simpleType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="plan" type="{http://www.tibco.com/ps/deploytool/modules}IntrospectDataSourcePlanType"/&amp;gt;
 *         &amp;lt;element name="genericAttribute" type="{http://www.tibco.com/ps/deploytool/modules}AttributeDefType" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntrospectDataSourceType", propOrder = {
    "id",
    "resourcePath",
    "runInBackgroundTransaction",
    "reportDetail",
    "plan",
    "genericAttribute"
})
public class IntrospectDataSourceType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String resourcePath;
    @XmlElement(defaultValue = "false")
    protected Boolean runInBackgroundTransaction;
    @XmlElement(required = true)
    protected String reportDetail;
    @XmlElement(required = true)
    protected IntrospectDataSourcePlanType plan;
    protected List<AttributeDefType> genericAttribute;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the resourcePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * Sets the value of the resourcePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcePath(String value) {
        this.resourcePath = value;
    }

    /**
     * Gets the value of the runInBackgroundTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRunInBackgroundTransaction() {
        return runInBackgroundTransaction;
    }

    /**
     * Sets the value of the runInBackgroundTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunInBackgroundTransaction(Boolean value) {
        this.runInBackgroundTransaction = value;
    }

    /**
     * Gets the value of the reportDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportDetail() {
        return reportDetail;
    }

    /**
     * Sets the value of the reportDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportDetail(String value) {
        this.reportDetail = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link IntrospectDataSourcePlanType }
     *     
     */
    public IntrospectDataSourcePlanType getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntrospectDataSourcePlanType }
     *     
     */
    public void setPlan(IntrospectDataSourcePlanType value) {
        this.plan = value;
    }

    /**
     * Gets the value of the genericAttribute property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the genericAttribute property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getGenericAttribute().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeDefType }
     * 
     * 
     */
    public List<AttributeDefType> getGenericAttribute() {
        if (genericAttribute == null) {
            genericAttribute = new ArrayList<AttributeDefType>();
        }
        return this.genericAttribute;
    }

}
