//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Introspect Data Source Plan Entry Type: Provides an iteration of detailed entries for introspection.
 * 		
 * 
 * &lt;p&gt;Java class for IntrospectDataSourcePlanEntriesType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="IntrospectDataSourcePlanEntriesType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="planEntry" type="{http://www.tibco.com/ps/deploytool/modules}IntrospectDataSourcePlanEntryType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntrospectDataSourcePlanEntriesType", propOrder = {
    "planEntry"
})
public class IntrospectDataSourcePlanEntriesType {

    protected IntrospectDataSourcePlanEntryType planEntry;

    /**
     * Gets the value of the planEntry property.
     * 
     * @return
     *     possible object is
     *     {@link IntrospectDataSourcePlanEntryType }
     *     
     */
    public IntrospectDataSourcePlanEntryType getPlanEntry() {
        return planEntry;
    }

    /**
     * Sets the value of the planEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntrospectDataSourcePlanEntryType }
     *     
     */
    public void setPlanEntry(IntrospectDataSourcePlanEntryType value) {
        this.planEntry = value;
    }

}
