//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.19 at 12:55:18 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/ps/deploytool/modules")
package com.tibco.ps.deploytool.modules;
