//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Resource Privilege Type: Documentation goes here.
 * 			
 * 
 * &lt;p&gt;Java class for PrivilegeEntryType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="PrivilegeEntryType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="resourcePath" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="resourceType" type="{http://www.tibco.com/ps/deploytool/modules}ResourceTypeSimpleType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="resourceOwner" type="{http://www.tibco.com/ps/deploytool/modules}ResourceOwnerType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="recurse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="updateDependenciesRecursively" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="updateDependentsRecursively" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="mode" type="{http://www.tibco.com/ps/deploytool/modules}PrivilegeModeValidationList" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="privilege" type="{http://www.tibco.com/ps/deploytool/modules}PrivilegeType" maxOccurs="unbounded"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrivilegeEntryType", propOrder = {
    "id",
    "resourcePath",
    "resourceType",
    "resourceOwner",
    "recurse",
    "updateDependenciesRecursively",
    "updateDependentsRecursively",
    "mode",
    "privilege"
})
public class PrivilegeEntryType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String resourcePath;
    @XmlSchemaType(name = "string")
    protected ResourceTypeSimpleType resourceType;
    protected ResourceOwnerType resourceOwner;
    protected Boolean recurse;
    protected Boolean updateDependenciesRecursively;
    protected Boolean updateDependentsRecursively;
    @XmlSchemaType(name = "string")
    protected PrivilegeModeValidationList mode;
    @XmlElement(required = true)
    protected List<PrivilegeType> privilege;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the resourcePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * Sets the value of the resourcePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcePath(String value) {
        this.resourcePath = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceTypeSimpleType }
     *     
     */
    public ResourceTypeSimpleType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceTypeSimpleType }
     *     
     */
    public void setResourceType(ResourceTypeSimpleType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the resourceOwner property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceOwnerType }
     *     
     */
    public ResourceOwnerType getResourceOwner() {
        return resourceOwner;
    }

    /**
     * Sets the value of the resourceOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceOwnerType }
     *     
     */
    public void setResourceOwner(ResourceOwnerType value) {
        this.resourceOwner = value;
    }

    /**
     * Gets the value of the recurse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecurse() {
        return recurse;
    }

    /**
     * Sets the value of the recurse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecurse(Boolean value) {
        this.recurse = value;
    }

    /**
     * Gets the value of the updateDependenciesRecursively property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateDependenciesRecursively() {
        return updateDependenciesRecursively;
    }

    /**
     * Sets the value of the updateDependenciesRecursively property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateDependenciesRecursively(Boolean value) {
        this.updateDependenciesRecursively = value;
    }

    /**
     * Gets the value of the updateDependentsRecursively property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateDependentsRecursively() {
        return updateDependentsRecursively;
    }

    /**
     * Sets the value of the updateDependentsRecursively property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateDependentsRecursively(Boolean value) {
        this.updateDependentsRecursively = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link PrivilegeModeValidationList }
     *     
     */
    public PrivilegeModeValidationList getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivilegeModeValidationList }
     *     
     */
    public void setMode(PrivilegeModeValidationList value) {
        this.mode = value;
    }

    /**
     * Gets the value of the privilege property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the privilege property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPrivilege().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link PrivilegeType }
     * 
     * 
     */
    public List<PrivilegeType> getPrivilege() {
        if (privilege == null) {
            privilege = new ArrayList<PrivilegeType>();
        }
        return this.privilege;
    }

}
