//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for PrivilegeValidationList.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="PrivilegeValidationList"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="NONE"/&amp;gt;
 *     &amp;lt;enumeration value="READ"/&amp;gt;
 *     &amp;lt;enumeration value="WRITE"/&amp;gt;
 *     &amp;lt;enumeration value="EXECUTE"/&amp;gt;
 *     &amp;lt;enumeration value="SELECT"/&amp;gt;
 *     &amp;lt;enumeration value="UPDATE"/&amp;gt;
 *     &amp;lt;enumeration value="INSERT"/&amp;gt;
 *     &amp;lt;enumeration value="DELETE"/&amp;gt;
 *     &amp;lt;enumeration value="GRANT"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "PrivilegeValidationList")
@XmlEnum
public enum PrivilegeValidationList {

    NONE,
    READ,
    WRITE,
    EXECUTE,
    SELECT,
    UPDATE,
    INSERT,
    DELETE,
    GRANT;

    public String value() {
        return name();
    }

    public static PrivilegeValidationList fromValue(String v) {
        return valueOf(v);
    }

}
