//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Rebind Type: The Rebind Type provides a choice between the traditional rebinding or the rebind resources in a folder.
 * 			
 * 
 * &lt;p&gt;Java class for RebindType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="RebindType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="rebindResource" type="{http://www.tibco.com/ps/deploytool/modules}RebindResourceType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="rebindFolder" type="{http://www.tibco.com/ps/deploytool/modules}RebindFolderType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RebindType", propOrder = {
    "rebindResource",
    "rebindFolder"
})
public class RebindType {

    protected RebindResourceType rebindResource;
    protected RebindFolderType rebindFolder;

    /**
     * Gets the value of the rebindResource property.
     * 
     * @return
     *     possible object is
     *     {@link RebindResourceType }
     *     
     */
    public RebindResourceType getRebindResource() {
        return rebindResource;
    }

    /**
     * Sets the value of the rebindResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link RebindResourceType }
     *     
     */
    public void setRebindResource(RebindResourceType value) {
        this.rebindResource = value;
    }

    /**
     * Gets the value of the rebindFolder property.
     * 
     * @return
     *     possible object is
     *     {@link RebindFolderType }
     *     
     */
    public RebindFolderType getRebindFolder() {
        return rebindFolder;
    }

    /**
     * Sets the value of the rebindFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link RebindFolderType }
     *     
     */
    public void setRebindFolder(RebindFolderType value) {
        this.rebindFolder = value;
    }

}
