//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				These security options provide the user with the ability to refine how the regression security is executed.
 * 			
 * 
 * &lt;p&gt;Java class for RegressionSecurityExecutionType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="RegressionSecurityExecutionType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="securityPlanIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="securityOverallRatingException" minOccurs="0"&amp;gt;
 *           &amp;lt;simpleType&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *               &amp;lt;enumeration value="yes"/&amp;gt;
 *               &amp;lt;enumeration value="no"/&amp;gt;
 *               &amp;lt;enumeration value="true"/&amp;gt;
 *               &amp;lt;enumeration value="false"/&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/simpleType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="securityExecutionErrorException" minOccurs="0"&amp;gt;
 *           &amp;lt;simpleType&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *               &amp;lt;enumeration value="yes"/&amp;gt;
 *               &amp;lt;enumeration value="no"/&amp;gt;
 *               &amp;lt;enumeration value="true"/&amp;gt;
 *               &amp;lt;enumeration value="false"/&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/simpleType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegressionSecurityExecutionType", propOrder = {
    "securityPlanIds",
    "securityOverallRatingException",
    "securityExecutionErrorException"
})
public class RegressionSecurityExecutionType {

    protected String securityPlanIds;
    protected String securityOverallRatingException;
    protected String securityExecutionErrorException;

    /**
     * Gets the value of the securityPlanIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPlanIds() {
        return securityPlanIds;
    }

    /**
     * Sets the value of the securityPlanIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPlanIds(String value) {
        this.securityPlanIds = value;
    }

    /**
     * Gets the value of the securityOverallRatingException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityOverallRatingException() {
        return securityOverallRatingException;
    }

    /**
     * Sets the value of the securityOverallRatingException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityOverallRatingException(String value) {
        this.securityOverallRatingException = value;
    }

    /**
     * Gets the value of the securityExecutionErrorException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityExecutionErrorException() {
        return securityExecutionErrorException;
    }

    /**
     * Sets the value of the securityExecutionErrorException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityExecutionErrorException(String value) {
        this.securityExecutionErrorException = value;
    }

}
