//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="regressionTest" type="{http://www.tibco.com/ps/deploytool/modules}RegressionTestType" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="regressionQueries" type="{http://www.tibco.com/ps/deploytool/modules}RegressionQueriesType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="regressionSecurity" type="{http://www.tibco.com/ps/deploytool/modules}RegressionSecurityType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regressionTest",
    "regressionQueries",
    "regressionSecurity"
})
@XmlRootElement(name = "RegressionModule")
public class RegressionModule {

    protected List<RegressionTestType> regressionTest;
    protected RegressionQueriesType regressionQueries;
    protected RegressionSecurityType regressionSecurity;

    /**
     * Gets the value of the regressionTest property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the regressionTest property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getRegressionTest().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link RegressionTestType }
     * 
     * 
     */
    public List<RegressionTestType> getRegressionTest() {
        if (regressionTest == null) {
            regressionTest = new ArrayList<RegressionTestType>();
        }
        return this.regressionTest;
    }

    /**
     * Gets the value of the regressionQueries property.
     * 
     * @return
     *     possible object is
     *     {@link RegressionQueriesType }
     *     
     */
    public RegressionQueriesType getRegressionQueries() {
        return regressionQueries;
    }

    /**
     * Sets the value of the regressionQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegressionQueriesType }
     *     
     */
    public void setRegressionQueries(RegressionQueriesType value) {
        this.regressionQueries = value;
    }

    /**
     * Gets the value of the regressionSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link RegressionSecurityType }
     *     
     */
    public RegressionSecurityType getRegressionSecurity() {
        return regressionSecurity;
    }

    /**
     * Sets the value of the regressionSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegressionSecurityType }
     *     
     */
    public void setRegressionSecurity(RegressionSecurityType value) {
        this.regressionSecurity = value;
    }

}
