//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.30 at 05:10:56 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Parameter settings for testing a regression test file.
 * 			
 * 
 * <p>Java class for RegressionTestRunParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegressionTestRunParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="functional"/>
 *               &lt;enumeration value="functional_as_is"/>
 *               &lt;enumeration value="migration"/>
 *               &lt;enumeration value="regression"/>
 *               &lt;enumeration value="performance"/>
 *               &lt;enumeration value="security"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logDelimiter" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="COMMA"/>
 *               &lt;enumeration value=","/>
 *               &lt;enumeration value="PIPE"/>
 *               &lt;enumeration value="|"/>
 *               &lt;enumeration value="TAB"/>
 *               &lt;enumeration value="TILDE"/>
 *               &lt;enumeration value="~"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logAppend">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="baseDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delimiter">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="COMMA"/>
 *               &lt;enumeration value=","/>
 *               &lt;enumeration value="PIPE"/>
 *               &lt;enumeration value="|"/>
 *               &lt;enumeration value="TAB"/>
 *               &lt;enumeration value="TILDE"/>
 *               &lt;enumeration value="~"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="printOutput">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="verbose"/>
 *               &lt;enumeration value="summary"/>
 *               &lt;enumeration value="silent"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="perfTestThreads" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="perfTestDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="perfTestSleepPrint" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="perfTestSleepExec" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="securityExecution" type="{http://www.tibco.com/ps/deploytool/modules}RegressionSecurityExecutionType" minOccurs="0"/>
 *         &lt;element name="runQueries">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="runProcedures">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="runWS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="useAllDatasources">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datasources" type="{http://www.tibco.com/ps/deploytool/modules}RegressionDatasourcesType" minOccurs="0"/>
 *         &lt;element name="resources" type="{http://www.tibco.com/ps/deploytool/modules}RegressionResourcesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegressionTestRunParamsType", propOrder = {
    "testType",
    "logFilePath",
    "logDelimiter",
    "logAppend",
    "baseDir",
    "delimiter",
    "printOutput",
    "perfTestThreads",
    "perfTestDuration",
    "perfTestSleepPrint",
    "perfTestSleepExec",
    "securityExecution",
    "runQueries",
    "runProcedures",
    "runWS",
    "useAllDatasources",
    "datasources",
    "resources"
})
public class RegressionTestRunParamsType {

    @XmlElement(required = true)
    protected String testType;
    @XmlElement(required = true)
    protected String logFilePath;
    protected String logDelimiter;
    @XmlElement(required = true)
    protected String logAppend;
    protected String baseDir;
    @XmlElement(required = true)
    protected String delimiter;
    @XmlElement(required = true)
    protected String printOutput;
    protected Integer perfTestThreads;
    protected Integer perfTestDuration;
    protected Integer perfTestSleepPrint;
    protected Integer perfTestSleepExec;
    protected RegressionSecurityExecutionType securityExecution;
    @XmlElement(required = true)
    protected String runQueries;
    @XmlElement(required = true)
    protected String runProcedures;
    @XmlElement(required = true)
    protected String runWS;
    @XmlElement(required = true)
    protected String useAllDatasources;
    protected RegressionDatasourcesType datasources;
    protected RegressionResourcesType resources;

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the logFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFilePath() {
        return logFilePath;
    }

    /**
     * Sets the value of the logFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFilePath(String value) {
        this.logFilePath = value;
    }

    /**
     * Gets the value of the logDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogDelimiter() {
        return logDelimiter;
    }

    /**
     * Sets the value of the logDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogDelimiter(String value) {
        this.logDelimiter = value;
    }

    /**
     * Gets the value of the logAppend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogAppend() {
        return logAppend;
    }

    /**
     * Sets the value of the logAppend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogAppend(String value) {
        this.logAppend = value;
    }

    /**
     * Gets the value of the baseDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDir() {
        return baseDir;
    }

    /**
     * Sets the value of the baseDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDir(String value) {
        this.baseDir = value;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelimiter(String value) {
        this.delimiter = value;
    }

    /**
     * Gets the value of the printOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOutput() {
        return printOutput;
    }

    /**
     * Sets the value of the printOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOutput(String value) {
        this.printOutput = value;
    }

    /**
     * Gets the value of the perfTestThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPerfTestThreads() {
        return perfTestThreads;
    }

    /**
     * Sets the value of the perfTestThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPerfTestThreads(Integer value) {
        this.perfTestThreads = value;
    }

    /**
     * Gets the value of the perfTestDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPerfTestDuration() {
        return perfTestDuration;
    }

    /**
     * Sets the value of the perfTestDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPerfTestDuration(Integer value) {
        this.perfTestDuration = value;
    }

    /**
     * Gets the value of the perfTestSleepPrint property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPerfTestSleepPrint() {
        return perfTestSleepPrint;
    }

    /**
     * Sets the value of the perfTestSleepPrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPerfTestSleepPrint(Integer value) {
        this.perfTestSleepPrint = value;
    }

    /**
     * Gets the value of the perfTestSleepExec property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPerfTestSleepExec() {
        return perfTestSleepExec;
    }

    /**
     * Sets the value of the perfTestSleepExec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPerfTestSleepExec(Integer value) {
        this.perfTestSleepExec = value;
    }

    /**
     * Gets the value of the securityExecution property.
     * 
     * @return
     *     possible object is
     *     {@link RegressionSecurityExecutionType }
     *     
     */
    public RegressionSecurityExecutionType getSecurityExecution() {
        return securityExecution;
    }

    /**
     * Sets the value of the securityExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegressionSecurityExecutionType }
     *     
     */
    public void setSecurityExecution(RegressionSecurityExecutionType value) {
        this.securityExecution = value;
    }

    /**
     * Gets the value of the runQueries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunQueries() {
        return runQueries;
    }

    /**
     * Sets the value of the runQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunQueries(String value) {
        this.runQueries = value;
    }

    /**
     * Gets the value of the runProcedures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunProcedures() {
        return runProcedures;
    }

    /**
     * Sets the value of the runProcedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunProcedures(String value) {
        this.runProcedures = value;
    }

    /**
     * Gets the value of the runWS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunWS() {
        return runWS;
    }

    /**
     * Sets the value of the runWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunWS(String value) {
        this.runWS = value;
    }

    /**
     * Gets the value of the useAllDatasources property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseAllDatasources() {
        return useAllDatasources;
    }

    /**
     * Sets the value of the useAllDatasources property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseAllDatasources(String value) {
        this.useAllDatasources = value;
    }

    /**
     * Gets the value of the datasources property.
     * 
     * @return
     *     possible object is
     *     {@link RegressionDatasourcesType }
     *     
     */
    public RegressionDatasourcesType getDatasources() {
        return datasources;
    }

    /**
     * Sets the value of the datasources property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegressionDatasourcesType }
     *     
     */
    public void setDatasources(RegressionDatasourcesType value) {
        this.datasources = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link RegressionResourcesType }
     *     
     */
    public RegressionResourcesType getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegressionResourcesType }
     *     
     */
    public void setResources(RegressionResourcesType value) {
        this.resources = value;
    }

}
