//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This is a list of resources for which use as a filter against the actual Composite datasource(s) to perform comparisons or test executions.  
 * 				A wild card ".*" may be used at the catalog or schema level to denote that all resources under that level should be compared or executed.  
 * 				A fully qualified resource may be identified as well. This of this as a filter that can be fine-tuned for one or more resources. 
 * 				If left empty then all resources are compared or executed. Overlapping resource wild cards will use the highest level specified in this list.					
 * 					Examples: 
 * 					CAT.* (include all resources under the catalog CAT), 
 * 					CAT.SCHEMA.* (include all resources under the schema located at CAT.SCHEMA)
 * 					CAT.SCHEMA.VIEW1 (include the resource specified by CAT.SCHEMA.VIEW1)
 * 			
 * 
 * &lt;p&gt;Java class for RegressionResourcesType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="RegressionResourcesType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegressionResourcesType", propOrder = {
    "resource"
})
public class RegressionResourcesType {

    protected List<String> resource;

    /**
     * Gets the value of the resource property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the resource property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getResource().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResource() {
        if (resource == null) {
            resource = new ArrayList<String>();
        }
        return this.resource;
    }

}
