//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:40:03 PM EDT 
//


package com.tibco.ps.deploytool.modules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="triggerList" type="{http://www.tibco.com/ps/deploytool/modules}TriggerListType"/&amp;gt;
 *         &amp;lt;element name="scheduleList" type="{http://www.tibco.com/ps/deploytool/modules}TriggerScheduleListType"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "triggerList",
    "scheduleList"
})
@XmlRootElement(name = "TriggerModule")
public class TriggerModule {

    @XmlElement(required = true)
    protected TriggerListType triggerList;
    @XmlElement(required = true)
    protected TriggerScheduleListType scheduleList;

    /**
     * Gets the value of the triggerList property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerListType }
     *     
     */
    public TriggerListType getTriggerList() {
        return triggerList;
    }

    /**
     * Sets the value of the triggerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerListType }
     *     
     */
    public void setTriggerList(TriggerListType value) {
        this.triggerList = value;
    }

    /**
     * Gets the value of the scheduleList property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerScheduleListType }
     *     
     */
    public TriggerScheduleListType getScheduleList() {
        return scheduleList;
    }

    /**
     * Sets the value of the scheduleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerScheduleListType }
     *     
     */
    public void setScheduleList(TriggerScheduleListType value) {
        this.scheduleList = value;
    }

}
